Add failing regression test for #718
[InterfaceMember] and [Template] with same name cause
InvalidOperationException: Sequence contains more than one element